/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Inserciones;
import Controlador.SqlDirectorTecnico;
import Modelo.DirectorTecnico;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUNIOR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        PersonaContent p1=new PersonaContent();
        ShowPanel(p1);
        p1.listar();
        /*para insertar datos*/
        Inserciones.InsertDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Persona = new javax.swing.JButton();
        DrTecnico = new javax.swing.JButton();
        Jugador = new javax.swing.JButton();
        Equipo = new javax.swing.JButton();
        PartidoEquipo = new javax.swing.JButton();
        Partido = new javax.swing.JButton();
        Gol = new javax.swing.JButton();
        Consultas = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TORNEO ");
        setPreferredSize(new java.awt.Dimension(790, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(785, 550));

        Persona.setBackground(new java.awt.Color(204, 204, 204));
        Persona.setForeground(new java.awt.Color(0, 0, 0));
        Persona.setText("Personas");
        Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaActionPerformed(evt);
            }
        });

        DrTecnico.setBackground(new java.awt.Color(204, 204, 204));
        DrTecnico.setForeground(new java.awt.Color(0, 0, 0));
        DrTecnico.setText("Dt. Tecnico");
        DrTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrTecnicoActionPerformed(evt);
            }
        });

        Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Jugador.setForeground(new java.awt.Color(0, 0, 0));
        Jugador.setText("Jugadores");
        Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorActionPerformed(evt);
            }
        });

        Equipo.setBackground(new java.awt.Color(204, 204, 204));
        Equipo.setForeground(new java.awt.Color(0, 0, 0));
        Equipo.setText("Equipos");
        Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoActionPerformed(evt);
            }
        });

        PartidoEquipo.setBackground(new java.awt.Color(204, 204, 204));
        PartidoEquipo.setForeground(new java.awt.Color(0, 0, 0));
        PartidoEquipo.setText("Partido Equipos");
        PartidoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoEquipoActionPerformed(evt);
            }
        });

        Partido.setBackground(new java.awt.Color(204, 204, 204));
        Partido.setForeground(new java.awt.Color(0, 0, 0));
        Partido.setText("Partidos");
        Partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoActionPerformed(evt);
            }
        });

        Gol.setBackground(new java.awt.Color(204, 204, 204));
        Gol.setForeground(new java.awt.Color(0, 0, 0));
        Gol.setText("Goles");
        Gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolActionPerformed(evt);
            }
        });

        Consultas.setBackground(new java.awt.Color(204, 204, 204));
        Consultas.setForeground(new java.awt.Color(0, 0, 0));
        Consultas.setText("Consultas");
        Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultasActionPerformed(evt);
            }
        });

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(0, 0, 0));
        content.setPreferredSize(new java.awt.Dimension(795, 490));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Persona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DrTecnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Equipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PartidoEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Partido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Gol, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Consultas)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DrTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PartidoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartidoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoEquipoActionPerformed
         PartidoEquipoContent p7=new PartidoEquipoContent();
        ShowPanel(p7);
        p7.listar();
    }//GEN-LAST:event_PartidoEquipoActionPerformed

    private void ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultasActionPerformed
        ConsultasContent p8=new ConsultasContent();
        ShowPanel(p8);
        p8.ConsultaUno();
         p8.ConsultaDos();
          p8.ConsultaTres();
          p8.ConsultaCuatro();
          p8.ConsultaCinco();
          p8.ConsultaSeis();
    }//GEN-LAST:event_ConsultasActionPerformed

    private void PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaActionPerformed
        PersonaContent p1=new PersonaContent();
        ShowPanel(p1);
        p1.listar();
    }//GEN-LAST:event_PersonaActionPerformed
    
    private void DrTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrTecnicoActionPerformed
         TecnicoContent p2=new TecnicoContent();
         ShowPanel(p2);
         p2.listar();
    }//GEN-LAST:event_DrTecnicoActionPerformed

    private void JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorActionPerformed
         JugadorContent p3=new JugadorContent();
         ShowPanel(p3);
         p3.listar();
    }//GEN-LAST:event_JugadorActionPerformed

    private void EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoActionPerformed
        EquipoContent p4=new EquipoContent();
        ShowPanel(p4);
        p4.listar();
    }//GEN-LAST:event_EquipoActionPerformed

    private void PartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoActionPerformed
        PartidoContent p5=new PartidoContent();
        ShowPanel(p5);
        p5.listar();
    }//GEN-LAST:event_PartidoActionPerformed

    private void GolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolActionPerformed
       GolContent p6=new GolContent();
        ShowPanel(p6);
        p6.listar();
    }//GEN-LAST:event_GolActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void ShowPanel(JPanel p){        
       
        p.setSize(785, 490);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
            
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultas;
    private javax.swing.JButton DrTecnico;
    private javax.swing.JButton Equipo;
    private javax.swing.JButton Gol;
    private javax.swing.JButton Jugador;
    private javax.swing.JButton Partido;
    private javax.swing.JButton PartidoEquipo;
    private javax.swing.JButton Persona;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
